services:

  mariadb:
    container_name: mariadb
    networks:
      - inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - ../.env
    expose:
      - "3306"

  nginx:
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - inception

  wordpress:
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress  
    expose:
      - "9000"
    networks:
      - inception

# Linking the containers
networks:
  inception:
    name: inception
    driver: bridge